### ISSUE TITLE
VIAudioDeviceManager.getActiveDevice() => Unhandled Exception

### ISSUE THREAD

**Issue by ivanesi** [voximplant/flutter_voximplant#16]
Got the exception when run this:

```dart
final audioDeviceManager = Voximplant().getAudioDeviceManager();
audioDeviceManager.onAudioDeviceChanged = _onAudioDeviceChanged;
final device = audioDeviceManager.getActiveDevice();
```

```
E/flutter (30765): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
E/flutter (30765): #0      MethodChannel._invokeMethod package:flutter/…/services/platform_channel.dart:159
E/flutter (30765): <asynchronous suspension>
E/flutter (30765): #1      MethodChannel.invokeMethod package:flutter/…/services/platform_channel.dart:332
E/flutter (30765): #2      MethodChannel.invokeMapMethod package:flutter/…/services/platform_channel.dart:359
E/flutter (30765): #3      VIAudioDeviceManager.getActiveDevice package:flutter_voximplant/…/hardware/audio_device_manager.dart:127
```

- flutter_voximplant: ^2.3.0
- Pixel on Android 10

**Comment by ivanesi** [comment]
исправлено в `flutter_voximplant: ^2.4.1`
